In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.compat.v1.disable_eager_execution()
data_input_x = np.array([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
data_input_x
data_input_y=np.array([[0.0],[0.0],[0.0],[1.0]])
data_input_y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [3]:
def step_function(sum_value):
  return tf.cast(tf.compat.v1.to_float(tf.math.greater_equal(sum_value,1)), tf.float64)

In [4]:
Weights = tf.Variable(tf.zeros([2,1],dtype=tf.float64))
output_layer = tf.matmul(data_input_x,Weights)
predictions = step_function(output_layer)

Instructions for updating:
Use `tf.cast` instead.


In [5]:
error=tf.subtract(data_input_y, predictions)

delta = tf.matmul(data_input_x, error, transpose_a=True)

learning_rate = 0.1
train = tf.compat.v1.assign(Weights, tf.multiply(delta, learning_rate))
init = tf.compat.v1.global_variables_initializer()


In [6]:
with tf.compat.v1.Session() as s:
  s.run(init)  
  print('Output layer result: \n', s.run(output_layer))
  print('Prediction result: \n', s.run(predictions))
  print('Error result: \n ', s.run(error))
  print('\n')
  for epoch in range(15):
    train_error, _= s.run([error, train])
    train_error_sum = tf.reduce_sum(train_error)
    print("Epoch: ", epoch+1, "- Error:", s.run(train_error_sum))
    if train_error_sum.eval() == 0.0:
      break;
  print("\n Weights to the best accuracy: \n", s.run(Weights))    




Output layer result: 
 [[0.]
 [0.]
 [0.]
 [0.]]
Prediction result: 
 [[0.]
 [0.]
 [0.]
 [0.]]
Error result: 
  [[0.]
 [0.]
 [0.]
 [1.]]


Epoch:  1 - Error: 1.0
Epoch:  2 - Error: 1.0
Epoch:  3 - Error: 1.0
Epoch:  4 - Error: 1.0
Epoch:  5 - Error: 1.0
Epoch:  6 - Error: 1.0
Epoch:  7 - Error: 1.0
Epoch:  8 - Error: 1.0
Epoch:  9 - Error: 1.0
Epoch:  10 - Error: 1.0
Epoch:  11 - Error: 1.0
Epoch:  12 - Error: 1.0
Epoch:  13 - Error: 1.0
Epoch:  14 - Error: 1.0
Epoch:  15 - Error: 1.0

 Weights to the best accuracy: 
 [[0.1]
 [0.1]]
