In [1]:
import tensorflow as tf

In [2]:
tf.compat.v1.disable_eager_execution()
a=tf.constant(5)
b=tf.constant(2)
c=tf.constant(3)
d=tf.multiply(a,b)
e=tf.add(c,b)
f=tf.subtract(d,e)
with tf.compat.v1.Session() as sess:
  print(sess.run(f))
  print(f.eval())
sess.close()

5
5


In [5]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]
    ]
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")


ValueError: Expected values [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]] to be a dense tensor with shape [4, 4], but got shape [4].


C:\Users\navin\Envs\jupyter\lib\site-packages\tensorflow\python\framework\tensor_util.py:454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nparray = np.array(values, dtype=np_dt)


In [6]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

tf.RaggedTensor(values=Tensor("RaggedConstant/values:0", shape=(10,), dtype=int32), row_splits=Tensor("RaggedConstant/Const:0", shape=(5,), dtype=int64))


In [7]:
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

Tensor("Const_6:0", shape=(), dtype=string)


In [ ]:
tensor_of_string = tf.constant(["Gray wolf",
                                "Quick Born",
                                "Lazy Dog"])
print(tensor_of_string)

tf.Tensor([b'Gray wolf' b'Quick Born' b'Lazy Dog'], shape=(3,), dtype=string)


In [ ]:
print(tf.strings.split(scalar_string_tensor), sep=" ")

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [ ]:
print(tf.strings.split(tensor_of_string))

<tf.RaggedTensor [[b'Gray', b'wolf'],
 [b'Quick', b'Born'],
 [b'Lazy', b'Dog']]>


In [ ]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [ ]:
byte_string = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_string)
print("Bytes:",byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [ ]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1,2],
                                       dense_shape=[3,4])
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [ ]:
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
n = int(input("Enter the size of array: "))
k = int(input("How many element do you want to insert into array: "))
arr = list(map(int,input().split()))
for i in range(n-k):
  arr.append(0)
print(arr)
n1 = int(input("Enter the number you want to insert: "))
if n1<n:
    index = n%n1-1
else:
    index = n1%n-1
print(index)
arr = arr[:index]+[n1]+arr[index+1:]
print(arr)


Enter the size of array: 15
How many element do you want to insert into array: 3
12 23 34
[12, 23, 34, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Enter the number you want to insert: 71
10
[12, 23, 34, 0, 0, 0, 0, 0, 0, 0, 71, 0, 0, 0, 0]
