In [1]:
# Forward Pass
import numpy as np

inp=np.array([[0.35,0.9]])
t=np.array([[0.5]])
w_h=np.array(([[0.1,0.4],[0.8, 0.6]]))
w_o=np.array([[0.3],[0.9]])

# Summation at hidden layer
s_h=np.dot(inp,w_h)
print(s_h)

#Activation at hidden layer
a_h=1/(1+np.exp(-s_h))
print(a_h)

#Summation at output layer
s_o=np.dot(a_h,w_o)
print(s_o)

#Activation at output layer
a_o=1/(1+np.exp(-s_o))
print(a_o)

[[0.755 0.68 ]]
[[0.6802672 0.6637387]]
[[0.80144499]]
[[0.69028349]]


In [2]:
# Backward Pass

e=t[0,:]-a_o[0,:]
print(e)

e_o=a_o*(1-a_o)*e
print(e_o)

#Weight Updtion at output layer
w_o+=1*e_o*(a_h.T)
print(w_o)

#Weight updation at hidden layer
e_h= a_h*(1-a_h)*(w_o.T*e_o)
print(e_h)

[-0.19028349]
[[-0.04068113]]
[[0.27232597]
 [0.87299836]]
[[-0.00240962 -0.00792648]]


In [3]:
w_h+=1*inp*e_h
print(w_h)

[[0.09915663 0.39286617]
 [0.79915663 0.59286617]]


In [1]:
import numpy as np

def sigmoidal(x):
    return 1/(1+np.exp(-x))

def derivative(x):
    return x*(1-x)

x = np.array([[0.35,0.9]])  #input
y = np.array([[0.5]]) #target
h_l = 2  #no. of hidden node
o_l = 1 #no. of output node
epoch = 3
l_r = 1  #Learning Rate
w_h = np.array(([[0.1,0.4],[0.8, 0.6]]))
w_o = np.array([[0.3],[0.9]])   #2x1

for i in range(epoch):
    print('Epoch --->> ',i+1)
    for j in range(x.shape[0]):
# Forward Pass

        # summation of hidden layer
        sum_h = np.dot(x[j,:],w_h)
        # output at hidden layer
        h_o = sigmoidal(sum_h) 
        # summation of output layer 
        sum_o = np.dot(h_o,w_o)
        # output at output layer 
        o_o = sigmoidal(sum_o)
        error = y[j,:]-o_o
        print("Input is ",x[j,:]," target is ",y[j,:], 'Output is ', o_o, 'Error is ',error)

# Backward Pass 
        if error!=0:
            # Error at output layer
            outDelta = derivative(o_o)*error
            # weight update at output layer 
            w_o += l_r*outDelta*h_o.reshape(2,1)
            # Error at hidden Layer
            hiddenDelta = derivative(h_o)*(w_o.T*outDelta)
            w_h += l_r*hiddenDelta*x[j,:]
            print(w_o,w_h)
  

Epoch --->>  1
Input is  [0.35 0.9 ]  target is  [0.5] Output is  [0.69028349] Error is  [-0.19028349]
[[0.27232597]
 [0.87299836]] [[0.09915663 0.39286617]
 [0.79915663 0.59286617]]
Epoch --->>  2
Input is  [0.35 0.9 ]  target is  [0.5] Output is  [0.68198189] Error is  [-0.18198189]
[[0.24548575]
 [0.84688012]] [[0.09841876 0.3861325 ]
 [0.79841876 0.5861325 ]]
Epoch --->>  3
Input is  [0.35 0.9 ]  target is  [0.5] Output is  [0.67386354] Error is  [-0.17386354]
[[0.21950901]
 [0.82166675]] [[0.0977798  0.37979047]
 [0.7977798  0.57979047]]
