In [151]:
import numpy as np

def sigmoidal(x):
    return 1/(1+np.exp(-x))

def derivative(x):
    return x*(1-x)

x = np.array([[0,0],[0,1],[1,0],[1,1]])  #input
y = np.array([[0],[1],[1],[0]]) #target
h_l = 2  #no. of hidden node
o_l = 1 #no. of output node
epoch = 3
l_r = 0.5  #Learning Rate
w_h = np.random.randn(h_l, x.shape[1]) 
w_o = np.random.randn(h_l, o_l)   #2x1

for i in range(epoch):
    print('Epoch --->> ',i+1)
    for j in range(x.shape[0]):
# Forward Pass

        # summation of hidden layer
        sum_h = np.dot(x[j,:],w_h)
        # output at hidden layer
        h_o = sigmoidal(sum_h) 
        # summation of output layer 
        sum_o = np.dot(h_o,w_o)
        # output at output layer 
        o_o = sigmoidal(sum_o)
        error = y[j,:]-o_o
        print("Input is ",x[j,:]," target is ",y[j,:], 'Output is ', o_o, 'Error is ',error)

# Backward Pass 
        if error!=0:
            # Error at output layer
            outDelta = derivative(o_o)*error
            # weight update at output layer 
            w_o += l_r*outDelta*h_o.reshape(2,1)
            # Error at hidden Layer
            hiddenDelta = derivative(h_o)*(w_o.T*outDelta)
            w_h += l_r*hiddenDelta*x[j,:]
            print(w_o,w_h)
            

Epoch --->>  1
Input is  [0 0]  target is  [0] Output is  [0.85724895] Error is  [-0.85724895]
[[3.03988723]
 [0.49291294]] [[ 0.00988058  0.47802094]
 [-0.52732346  0.26162465]]
Input is  [0 1]  target is  [1] Output is  [0.80325145] Error is  [0.19674855]
[[3.04565734]
 [0.5016975 ]] [[ 0.00988058  0.47993791]
 [-0.52732346  0.26354163]]
Input is  [1 0]  target is  [1] Output is  [0.86298029] Error is  [0.13701971]
[[3.04972784]
 [0.50670174]] [[ 0.01605687  0.47993791]
 [-0.52114718  0.26354163]]
Input is  [1 1]  target is  [0] Output is  [0.81625391] Error is  [-0.81625391]
[[3.02669089]
 [0.46521473]] [[-0.02742792  0.47371849]
 [-0.56463196  0.2573222 ]]
Epoch --->>  2
Input is  [0 0]  target is  [0] Output is  [0.85144161] Error is  [-0.85144161]
[[2.99976643]
 [0.43829027]] [[-0.02742792  0.47371849]
 [-0.56463196  0.2573222 ]]
Input is  [0 1]  target is  [1] Output is  [0.79158905] Error is  [0.20841095]
[[3.0059979 ]
 [0.44798583]] [[-0.02742792  0.47561234]
 [-0.56463196  0.

In [142]:
np.array([0.91470389, 0.88575848])*np.array([[-0.44585861],
       [ 0.6311631 ]])

array([[-0.4078286 , -0.39492304],
       [ 0.57732734,  0.55905807]])

In [146]:
derivative(h_o)*(w_o.T*deltaOut)

array([[ 0.00483403, -0.00887531]])