In [1]:
"""Crow search
   f(x)=x1^2+x1*x3+2x2^2
   objective is minimize the equation
   lb=-5, ub=5
   Population size=5"""
import numpy as np
ap=np.random.random(size=(5,))
x=np.random.uniform(low=-5, high=5,size=(5,3))
m=x.copy()
print("Awerness Probability\n",ap)
print("Current solns\n",x)
print("Memory\n",m)

Awerness Probability
 [0.42521717 0.86145971 0.5184191  0.72664993 0.39612136]
Current solns
 [[-1.36696238  0.02575591  0.61375594]
 [-4.36675625  1.21716411 -1.42725217]
 [ 1.12430884 -0.87968112  0.35062411]
 [-4.74544006 -1.5605034  -4.25262625]
 [-1.51589651  0.21812392 -2.71863029]]
Memory
 [[-1.36696238  0.02575591  0.61375594]
 [-4.36675625  1.21716411 -1.42725217]
 [ 1.12430884 -0.87968112  0.35062411]
 [-4.74544006 -1.5605034  -4.25262625]
 [-1.51589651  0.21812392 -2.71863029]]


In [2]:
fitness=[]
for i in x:
    fitness.append(1/(1+i[0]**2+2*i[1]**2+i[0]*i[2]))
print(fitness)

[0.4923848759104023, 0.03417167921902301, 0.23775796705735755, 0.02058878742046704, 0.13308029497689647]


In [6]:
iter=3
import random
for i in range(iter):
    print("Iteration is ",i+1)
    for j in range(5):
        while True:
            k=random.randint(0,4)
            if(k!=j):
                break
        r=random.random()
        if(r>=ap[k]):
            x[j,:]+=random.random()*(m[k,:]-x[j,:])
        else:
            x[j,:]=np.random.uniform(low=-5, high=5,size=(1,3))
        fitness_new=1/(1/(1+x[j,0]**2+2*x[j,1]**2+x[j,0]*x[j,2]))
        if(fitness_new>fitness[j]):
            fitness[j]=fitness_new
            m[j,:]=x[j,:]
    print("Current solutions\n",x)
    print("Memory \n",m)
    print("--------------------------------")
    
    

Iteration is  1
Current solutions
 [[ 2.49769693  1.6706566   1.5009773 ]
 [-0.20860983  0.34420095  0.50327921]
 [-1.20407044 -2.39365369  2.35664634]
 [-3.82841567  0.38671808 -2.28070029]
 [-2.50790767 -1.81960773 -2.87255616]]
Memory 
 [[ 2.49769693  1.6706566   1.5009773 ]
 [-0.20860983  0.34420095  0.50327921]
 [-1.20407044 -2.39365369  2.35664634]
 [-3.82841567  0.38671808 -2.28070029]
 [-2.50790767 -1.81960773 -2.87255616]]
--------------------------------
Iteration is  2
Current solutions
 [[ 2.46553208  1.11089178  4.86906582]
 [-0.42562366  0.34674993  0.33637466]
 [-1.78142468 -2.13945948  0.04109486]
 [-1.1123015   0.69923076  0.804737  ]
 [ 0.47242822  3.33862467  3.22820026]]
Memory 
 [[ 2.46553208  1.11089178  4.86906582]
 [-0.42562366  0.34674993  0.33637466]
 [-1.78142468 -2.13945948  0.04109486]
 [-3.82841567  0.38671808 -2.28070029]
 [ 0.47242822  3.33862467  3.22820026]]
--------------------------------
Iteration is  3
Current solutions
 [[ 2.39037273  1.05336959  

In [2]:
import random
random.randint(0,5)

2