In [5]:
#PERCEPTRON FOR OR GATE USING delta RULE
import numpy as np
x=np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y=np.array([[0],[1],[1],[1]],dtype=np.float32)
w=np.array([0,0,0],dtype=np.float32) # first two elements are w1 and w2 and 3rd is bias
for j in range(3):
    print("Epoch is ",j+1)
    for i in range(x.shape[0]):
        print("Input is ",x[i,:]," Target is ",y[i,:])
        s=np.dot(x[i,:],w[0:2])+w[2]
        if(s>=1):
            out=1
        else:
            out=0
        err=y[i,:]-out
        print("Output is ",out, "error is ",y[i,:]-out)
        if(y[i,:]!=out):
            w[0:2]+=0.5*x[i,:]*err
            w[2]+=0.5*err
        print("weights and bias ",w)
    print("---------------------------------------")

Epoch is  1
Input is  [0. 0.]  Target is  [0.]
Output is  0 error is  [0.]
weights and bias  [0. 0. 0.]
Input is  [0. 1.]  Target is  [1.]
Output is  0 error is  [1.]
weights and bias  [0.  0.5 0.5]
Input is  [1. 0.]  Target is  [1.]
Output is  0 error is  [1.]
weights and bias  [0.5 0.5 1. ]
Input is  [1. 1.]  Target is  [1.]
Output is  1 error is  [0.]
weights and bias  [0.5 0.5 1. ]
---------------------------------------
Epoch is  2
Input is  [0. 0.]  Target is  [0.]
Output is  1 error is  [-1.]
weights and bias  [0.5 0.5 0.5]
Input is  [0. 1.]  Target is  [1.]
Output is  1 error is  [0.]
weights and bias  [0.5 0.5 0.5]
Input is  [1. 0.]  Target is  [1.]
Output is  1 error is  [0.]
weights and bias  [0.5 0.5 0.5]
Input is  [1. 1.]  Target is  [1.]
Output is  1 error is  [0.]
weights and bias  [0.5 0.5 0.5]
---------------------------------------
Epoch is  3
Input is  [0. 0.]  Target is  [0.]
Output is  0 error is  [0.]
weights and bias  [0.5 0.5 0.5]
Input is  [0. 1.]  Target is  [

In [7]:
import numpy as np    
class Perceptron(object):
    
    def __init__(self, eta=0.01, n_iter=10):
        self.eta = eta # Learning rate (between 0.0 and 1.0)
        self.n_iter = n_iter # Passes over the training dataset.
    def fit(self, X, y):
       
        self.w_ = np.zeros(1 + X.shape[1])
        
        for _ in range(self.n_iter):
            
            for xi, target in zip(X, y):
                print("input is ",xi,"target is ",target)
                print("output is ",self.predict(xi))
                error=target-self.predict(xi)
                print("Error is ",error)
                if error!=0:
                    update = self.eta * (target-self.predict(xi))
                    self.w_[1:] += update * xi
                    self.w_[0] += update*1
                print("Weights and bias ",self.w_)
                
                
            
        return self
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

import pandas as pd
import matplotlib.pyplot as plt
# inpur of 8 x 3
X=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
print(' Inputs : \n',X)
# target
y=np.array([-1,-1,-1,-1,1,1,1,1])
## call perceptron
ppn = Perceptron(eta=0.1, n_iter=2)
ppn.fit(X, y)
## predict o/ps
print('outpusts ', ppn.predict(X))
print(' output for [1,1,1] is ',ppn.predict([1,1,1]))
print(' output for [0,0,0] is ',ppn.predict([0,0,0])) # predicting o/p for given inputs


 Inputs : 
 [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
input is  [0 0 0] target is  -1
output is  1
Error is  -2
Weights and bias  [-0.2  0.   0.   0. ]
input is  [0 0 1] target is  -1
output is  -1
Error is  0
Weights and bias  [-0.2  0.   0.   0. ]
input is  [0 1 0] target is  -1
output is  -1
Error is  0
Weights and bias  [-0.2  0.   0.   0. ]
input is  [0 1 1] target is  -1
output is  -1
Error is  0
Weights and bias  [-0.2  0.   0.   0. ]
input is  [1 0 0] target is  1
output is  -1
Error is  2
Weights and bias  [0.  0.2 0.  0. ]
input is  [1 0 1] target is  1
output is  1
Error is  0
Weights and bias  [0.  0.2 0.  0. ]
input is  [1 1 0] target is  1
output is  1
Error is  0
Weights and bias  [0.  0.2 0.  0. ]
input is  [1 1 1] target is  1
output is  1
Error is  0
Weights and bias  [0.  0.2 0.  0. ]
input is  [0 0 0] target is  -1
output is  1
Error is  -2
Weights and bias  [-0.2  0.2  0.   0. ]
input is  [0 0 1] target is  -1
output is  -1
Error is  