In [1]:
# f(x)=a+2b+3c+4d-30
# Objective to minimize the equation

In [2]:
import numpy as np
import random as rd

In [3]:
population = np.zeros((10, 4), dtype=int)
for i in range(population.shape[0]):
    for j in range(population.shape[1]):
        population[i][j] = rd.randint(1,30)

In [4]:
# fitness = 1/(1+objective)
fitness = []
for i in population:
    val = i[0] + 2*i[1] + 3*i[2] + 4*i[3] - 30
    fit = 1/np.abs(1+val)
    fitness.append(fit)
    


In [5]:
# Selecion Operator
probablity = np.array(fitness/sum(fitness))
cumm_prob = []
j = 0
for i in probablity:
    if j == 0:
        cumm_prob.append(i)
        j += 1
    else:
        cumm_prob.append(i+cumm_prob[j-1])
        j += 1

In [6]:
# Parent selection
print("Cummlative Probabilities ",cumm_prob)
no_of_parents = 8
parents_crossover=np.zeros((8,4),dtype=np.int32)
for i in range(8):
    r = rd.random()
    print("Random number is",r)
    for j in range(10):
        if cumm_prob[j]>r:
            index = j
            break
    print("Chromosome selected", index)
    parents_crossover[i,:]=population[index,:]
print(parents_crossover)

Cummlative Probabilities  [0.07311069077953561, 0.2882248386500923, 0.3937525338318748, 0.46783157813166915, 0.5723730331715658, 0.6966612074967764, 0.7868703662812034, 0.8493616271151082, 0.9474838700034323, 1.0]
Random number is 0.2569558858683334
Chromosome selected 1
Random number is 0.6387765927716892
Chromosome selected 5
Random number is 0.6244723919289611
Chromosome selected 5
Random number is 0.5996622524082512
Chromosome selected 5
Random number is 0.6338375884596791
Chromosome selected 5
Random number is 0.14968434300969702
Chromosome selected 1
Random number is 0.34245959691924566
Chromosome selected 2
Random number is 0.4836235833992377
Chromosome selected 4
[[20  6 15  1]
 [10  6  7 19]
 [10  6  7 19]
 [10  6  7 19]
 [10  6  7 19]
 [20  6 15  1]
 [26  6  3 22]
 [11 24 23  2]]


In [7]:
# Single point crossover
off_spring=np.zeros((8,4), dtype=np.int32)

for i in range(0,8,2):
    pos=rd.randint(0,2)
    print(pos)
    off_spring[i,0:pos+1]=parents_crossover[i,0:pos+1]
    off_spring[i+1,0:pos+1]=parents_crossover[i+1,0:pos+1]
    off_spring[i,pos+1:]=parents_crossover[i+1,pos+1:]
    off_spring[i+1,pos+1:]=parents_crossover[i,pos+1:]
print(off_spring)

1
2
0
2
[[20  6  7 19]
 [10  6 15  1]
 [10  6  7 19]
 [10  6  7 19]
 [10  6 15  1]
 [20  6  7 19]
 [26  6  3  2]
 [11 24 23 22]]


In [8]:
#Mutation operator
for i in range(3):
    rand_r=rd.randint(0,7)
    rand_c=rd.randint(0,3)
    print("row is ",rand_r,"Column is ",rand_c)
    off_spring[rand_r,rand_c]=rd.randint(1,30)
print(off_spring)

row is  3 Column is  3
row is  3 Column is  3
row is  0 Column is  3
[[20  6  7  9]
 [10  6 15  1]
 [10  6  7 19]
 [10  6  7 20]
 [10  6 15  1]
 [20  6  7 19]
 [26  6  3  2]
 [11 24 23 22]]


In [9]:
# Fitness of offspring
fitness_offspring=[]
for i in off_spring:
    value=i[0]+2*i[1]+3*i[2]+4*i[3]-30
    fit=1/np.abs(1+value)
    fitness_offspring.append(fit)
print(fitness_offspring)

[0.016666666666666666, 0.023809523809523808, 0.011111111111111112, 0.010638297872340425, 0.023809523809523808, 0.01, 0.038461538461538464, 0.0053475935828877]
