In [8]:
import numpy as np
a1=np.array([1,2,3])
print(a1,a1.shape)

[1 2 3] (3,)


In [2]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [4]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros((4,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [9]:
np.random.random((2,3))

array([[0.76209966, 0.01212467, 0.05146768],
       [0.51122154, 0.61950324, 0.35126088]])

In [10]:
np.random.rand(5,5)

array([[0.80438845, 0.56213343, 0.77055944, 0.20705406, 0.1530844 ],
       [0.81931148, 0.11316976, 0.3512776 , 0.90349996, 0.13262508],
       [0.75291961, 0.32814433, 0.8231285 , 0.84556947, 0.88200784],
       [0.06667071, 0.51055917, 0.82636163, 0.8051228 , 0.957754  ],
       [0.8502445 , 0.74395842, 0.97424439, 0.25793773, 0.57659206]])

In [12]:
np.random.randn(5,5)

array([[-7.36294623e-02, -1.46474326e-01, -8.35473710e-01,
         2.56844351e-01,  9.50408843e-01],
       [ 2.83754225e-01,  1.23279054e+00,  7.33101906e-01,
         1.63261215e+00, -1.77627477e+00],
       [-4.10803628e-01,  8.66739176e-01, -1.68775028e+00,
         4.94182258e-01,  1.03124641e+00],
       [-5.98362358e-02, -1.41372229e-01,  4.75768089e-01,
        -6.51210542e-01, -7.15319653e-01],
       [-1.99225757e-01, -5.28247298e-01, -1.77876081e+00,
        -6.52556202e-01, -4.16894512e-04]])

In [13]:
np.random.randint(1,100)

67

In [14]:
np.random.randint(1,100,5)

array([58, 92, 43, 79, 41])

In [16]:
a4=np.zeros((3,5),dtype=np.int32)
for i in range(a4.shape[0]):
    a4[i,:]=np.random.randint(1,100,5)
print(a4)

[[11 56 78 53 21]
 [70 39 45 60 87]
 [62 70 76 70 80]]


In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.reshape(a4,(5,3))

array([[11, 56, 78],
       [53, 21, 70],
       [39, 45, 60],
       [87, 62, 70],
       [76, 70, 80]])

In [19]:
np.reshape(a4,(15,1))

array([[11],
       [56],
       [78],
       [53],
       [21],
       [70],
       [39],
       [45],
       [60],
       [87],
       [62],
       [70],
       [76],
       [70],
       [80]])

In [22]:
np.resize(a4,(5,5))

array([[11, 56, 78, 53, 21],
       [70, 39, 45, 60, 87],
       [62, 70, 76, 70, 80],
       [11, 56, 78, 53, 21],
       [70, 39, 45, 60, 87]])

In [26]:
print(a2)
print(np.max(a2,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [27]:
np.min(a2, axis=1)

array([1, 4, 7])

In [30]:
np.argmax(np.array([1,2,3,5,7,9,4]))

5

In [31]:
np.argmin(np.array([1,2,5,6,0,4,-3]))

6

In [32]:
np.mean(a2)

5.0

In [34]:
np.var(a2,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [35]:
np.std(a2)

2.581988897471611

In [36]:
np.sum(a2)

45

In [37]:
np.array([[1,2,3],[3,4,5]])+np.array([[1,1,1]])

array([[2, 3, 4],
       [4, 5, 6]])

In [38]:
np.array([[1,2,3],[3,4,5]])-np.array([[1,1,1]])

array([[0, 1, 2],
       [2, 3, 4]])

In [39]:
np.array([[1,2,3],[3,4,5]])*np.array([[1,1,1]])

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
np.dot(np.array([[1,2,3],[3,4,5]]),np.array([[1],[1],[1]]))

array([[ 6],
       [12]])

In [7]:
marks=np.random.randint(1,100,50)
print(marks)
# c=0
# c1=0
# for i in marks:
#     if(i<40):
#         c=c+1;
#     if(i>90):
#         c1=c1+1;
m1=[i for i in marks if(i<40)]
m2 =[i for i in marks if(i>90)]
print("below 40 = ",len(m1))
print("abaove 90 = ",len(m2))

[62 48 64 47 75 25 79  1 30 38 56 10 18 96 98 88 34 96 37 91 48 41 77 46
 98 39 82 37 33 94 78 10 70 80  1 34 96 58 91 85 31 20 51  9 87 95 17 47
 47 43]
below 40 =  18
abaove 90 =  9


In [12]:
a1 = np.array([10,20,30])
print(a1)

[10 20 30]


In [16]:
a=np.array([[1,2,3],[1,2,3]]) 
print(a)

[[1 2 3]
 [1 2 3]]


In [14]:
l1 = [10,20,30]
print(l1)

[10, 20, 30]


In [17]:
a2=np.array([[1,2,3],[4,5,6]]) 
print(a2, a2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [20]:
for i in range(a2.shape[0]): 
    for j in a2[i]: 
        print(j, end="") 
    print()

123
456


In [58]:
a3=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,8]]) 
print(a3)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 8]]


In [24]:
a3[:,1]     # array[rows,coloumn]

array([2, 5, 8])

In [43]:
a3[0:2,1:3]    #array[rows,coloumn] it will not include 2,3  0:1,1:2

array([[2, 3],
       [5, 6]])

In [54]:
print(np.linspace(0,50,20).shape[0])

20


In [62]:
a3.shape

(3, 4)