In [2]:
import numpy as np
class SOM:
    def __init__(self,ep,l=1.0):
        self.ep=ep
        self.l=l
    def Euclidean(self,x,w):
        s=0
        for i in range(len(x)):
            s+=(x[i]-w[i])**2
        return s
    def fit(self,x,w):
        self.w=w
        for i in range(self.ep):
            print("Epoch is ",i+1)
            
            for j in range(x.shape[0]):
                print("input is ",x[j,:])
                d=[]
                for k in range(self.w.shape[0]):
                    print(self.Euclidean(x[j,:],self.w[k,:]))
                    d.append(self.Euclidean(x[j,:],self.w[k,:]))
                print(d)
                index=np.argmin(d)
                print("Winner is ",index)
                self.w[index,:]+=l_r*(x[j,:]-self.w[index,:])
                print(self.w)
            print('--------------------')
            self.l*=0.5
    def predict(self,x):
        d=[]
        for k in range(self.w.shape[0]):
            #print(self.Euclidean(x,self.w[k,:]))
            d.append(self.Euclidean(x,self.w[k,:]))
        print(d)
        index=np.argmin(d)
        return ("Winner is "+str(index))
x=np.array([[1,1,0,0],[0,0,1,1]],dtype=np.float32)
w=np.array([[0.8,0.7,0.2,0.2],[0.1,0.2,0.3,0.4]])
l_r=1.0
sm=SOM(2,1)
sm.fit(x,w)
print(sm.predict(np.array([1,1,0,0], dtype=np.float32)))

Epoch is  1
input is  [1. 1. 0. 0.]
0.21000000000000002
1.7000000000000002
[0.21000000000000002, 1.7000000000000002]
Winner is  0
[[1.  1.  0.  0. ]
 [0.1 0.2 0.3 0.4]]
input is  [0. 0. 1. 1.]
4.0
0.8999999999999999
[4.0, 0.8999999999999999]
Winner is  1
[[1. 1. 0. 0.]
 [0. 0. 1. 1.]]
--------------------
Epoch is  2
input is  [1. 1. 0. 0.]
0.0
4.0
[0.0, 4.0]
Winner is  0
[[1. 1. 0. 0.]
 [0. 0. 1. 1.]]
input is  [0. 0. 1. 1.]
4.0
0.0
[4.0, 0.0]
Winner is  1
[[1. 1. 0. 0.]
 [0. 0. 1. 1.]]
--------------------
[0.0, 4.0]
Winner is 0
