In [1]:
import numpy as np
import random as rd
distance = np.array([[0,10,50,60,10],
                     [10,0,88,45,32],
                     [50,88,0,35,67],
                     [60,45,35,0,21],
                     [10,32,67,21,0]])

In [2]:
#  Population initialization
population_size = 6
chromosome_size = 5
population = np.zeros((population_size,chromosome_size),dtype=np.int32)
for i in range(population_size):
    l = [0,1,2,3,4]
    rd.shuffle(l)
    population[i] = l

In [3]:
# Fitness Evalution
def fitness(route):
    total_distance = 0
    for i in range(len(route)-1):
        total_distance += distance[route[i],route[i+1]]
    return 1/total_distance
fit = []
for i in population:
    fit.append(fitness(i))
print(fit)

[0.005813953488372093, 0.0044444444444444444, 0.005235602094240838, 0.00546448087431694, 0.005154639175257732, 0.0072992700729927005]


In [4]:
# Selection
def selection(population, fitness, no_of_parents):
    parent_selection = np.zeros((no_of_parents,population.shape[1]), dtype = np.int32)
    for i in range(no_of_parents):
        index = np.argmax(fitness)
        parent_selection[i] = population[index]
        fitness[index] = 0.00000
    return parent_selection
parent_selection = selection(population,fit.copy(),4)
print(parent_selection)

[[4 1 0 3 2]
 [4 2 3 0 1]
 [1 3 4 2 0]
 [3 4 1 2 0]]


In [5]:
# Crossover
def crossover(parent_selection):
    off_spring = np.zeros(parent_selection.shape, dtype = np.int32)
    for i in range(0, parent_selection.shape[0],2):
        r = rd.randint(0,3)
        print("Random Number is ", r)
        off_spring[i,:r+1] = parent_selection[i,:r+1]
        off_spring[i+1,:r+1] = parent_selection[i+1,:r+1]
        pos = r + 1
        for j in parent_selection[i+1]:
            if j not in off_spring[i,:pos]:
                off_spring[i][pos] = j
                pos += 1
    return off_spring

off_spring = crossover(parent_selection)
print(off_spring)

Random Number is  2
Random Number is  0
[[4 1 0 2 3]
 [4 2 3 0 0]
 [1 3 4 2 0]
 [3 0 0 0 0]]


In [6]:
# Mutation
def mutation(off_spring):
    rand_r = rd.randint(0, 3)
    c1 = rd.randint(0, 4)
    c2 = rd.randint(0, 4)
    print("Row: {} Column1: {} Column2: {}".format(rand_r,c1,c2))
    off_spring[rand_r, c1], off_spring[rand_r, c2] = off_spring[rand_r, c2], off_spring[rand_r, c1]

In [7]:
mutation(off_spring)
off_spring

Row: 2 Column1: 1 Column2: 4


array([[4, 1, 0, 2, 3],
       [4, 2, 3, 0, 0],
       [1, 0, 4, 2, 3],
       [3, 0, 0, 0, 0]])

In [8]:
print(fitness(off_spring))

[0.01298701 0.00724638 0.01098901 0.00666667 0.00555556]


In [9]:
print(fitness(parent_selection))

[0.01298701 0.00694444 0.00884956 0.00909091 0.01020408]
